FSDP/Controllers/OwnerVehiclesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FSDP.DATA.EF;
using Microsoft.AspNet.Identity;
using FSDP.Utilities;

namespace FSDP.Controllers
{
    public class OwnerVehiclesController : Controller
    {
        private FSDPEntities db = new FSDPEntities();

        // GET: OwnerVehicles
        [Authorize(Roles = "Owner, Admin")]
        public ActionResult Index()
        {
            string userID = User.Identity.GetUserId();
            UserDetail currentUser = db.UserDetails.Where(ud => ud.UserID == userID).FirstOrDefault();

            var ownerVehicles = db.OwnerVehicles.Where(x => x.OwnerID == currentUser.UserID);
            return View(ownerVehicles.ToList());
        }

        // GET: OwnerVehicles/Details/5
        [Authorize(Roles = "Owner, Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OwnerVehicle ownerVehicle = db.OwnerVehicles.Find(id);
            if (ownerVehicle == null)
            {
                return HttpNotFound();
            }
            return View(ownerVehicle);
        }

        // GET: OwnerVehicles/Create
        [Authorize(Roles = "Owner")]
        public ActionResult Create()
        {
            ViewBag.OwnerID = new SelectList(db.UserDetails, "UserID", "FirstName");
            return View();
        }

        // POST: OwnerVehicles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Owner")]
        //[ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OwnerVehicleID,Make,Model,OwnerID,CarPhoto,RequestedRepairs,IsActive,DateAdded")] OwnerVehicle ownerVehicle, HttpPostedFileBase carPhoto)
        {
                #region File Upload

                string file = "NoImage.png";
                if (carPhoto != null)
                {
                    file = carPhoto.FileName;
                    string ext = file.Substring(file.LastIndexOf('.'));
                    string[] goodExts = { ".jpeg", ".jpg", ".png", ".gif" };

                    if (goodExts.Contains(ext.ToLower()) && carPhoto.ContentLength <= 4194304)
                    {
                        file = Guid.NewGuid() + ext;

                        #region Resize Image
                        string savePath = Server.MapPath("~/Content/Images/VehicleImages/");                        Image convertedImage = Image.FromStream(carPhoto.InputStream);                        int maxImageSize = 500;                        int maxThumbSize = 100;                        ImageUtility.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);                        #endregion

                    }

                    ownerVehicle.CarPhoto = file;
                }

                #endregion

                ownerVehicle.OwnerID = User.Identity.GetUserId();
                ownerVehicle.DateAdded = DateTime.Now;

                db.OwnerVehicles.Add(ownerVehicle);
                db.SaveChanges();
                return RedirectToAction("Index");
        }

        //Get: Admin Edit
        public ActionResult AdminEdit (int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OwnerVehicle ownerVehicle = db.OwnerVehicles.Find(id);
            if (ownerVehicle == null)
            {
                return HttpNotFound();
            }
            return View(ownerVehicle);
        }

        // GET: OwnerVehicles/Edit/5
        [Authorize(Roles = "Owner, Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OwnerVehicle ownerVehicle = db.OwnerVehicles.Find(id);
            if (ownerVehicle == null)
            {
                return HttpNotFound();
            }
            ViewBag.OwnerID = new SelectList(db.UserDetails, "UserID", "FirstName", ownerVehicle.OwnerID);

            if (User.IsInRole("Admin"))
            {
                return View("AdminEdit", ownerVehicle);
            }

            return View(ownerVehicle);
        }

        // POST: OwnerVehicles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Owner, Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OwnerVehicleID,Make,Model,OwnerID,CarPhoto,RequestedRepairs,IsActive,DateAdded")] OwnerVehicle ownerVehicle, HttpPostedFileBase carPhoto)
        {
            if (User.IsInRole("Admin"))
            {
                db.Entry(ownerVehicle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("LocationSelect", "Reservations");
            }

            if (ModelState.IsValid)
            {

                #region File Upload

                string file = "NoImage.png";
                if (carPhoto != null)
                {
                    file = carPhoto.FileName;
                    string ext = file.Substring(file.LastIndexOf('.'));
                    string[] goodExts = { ".jpeg", ".jpg", ".png", ".gif" };

                    if (goodExts.Contains(ext.ToLower()) && carPhoto.ContentLength <= 4194304)
                    {
                        file = Guid.NewGuid() + ext;

                        #region Resize Image
                        string savePath = Server.MapPath("~/Content/Images/VehicleImages/");                        Image convertedImage = Image.FromStream(carPhoto.InputStream);                        int maxImageSize = 500;                        int maxThumbSize = 100;                        ImageUtility.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);                        #endregion

                    }

                    ownerVehicle.CarPhoto = file;
                }

                #endregion

                db.Entry(ownerVehicle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.OwnerID = new SelectList(db.UserDetails, "UserID", "FirstName", ownerVehicle.OwnerID);
            return View(ownerVehicle);
        }

        // GET: OwnerVehicles/Delete/5
        [Authorize(Roles = "Owner")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OwnerVehicle ownerVehicle = db.OwnerVehicles.Find(id);
            if (ownerVehicle == null)
            {
                return HttpNotFound();
            }
            return View(ownerVehicle);
        }

        // POST: OwnerVehicles/Delete/5
        [Authorize(Roles = "Owner")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OwnerVehicle ownerVehicle = db.OwnerVehicles.Find(id);
            db.OwnerVehicles.Remove(ownerVehicle);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FSDP/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FSDP.DATA.EF;
using Microsoft.AspNet.Identity;

namespace FSDP.Controllers
{
    public class ReservationsController : Controller
    {
        private FSDPEntities db = new FSDPEntities();

        [Authorize(Roles = "Owner")]
        public ActionResult OwnerReservation()
        {
            string userID = User.Identity.GetUserId();
            var reservations = db.Reservations.Where(r => r.IsComplete == false).Include(r => r.Location).Include(r => r.OwnerVehicle).Where(r => r.OwnerVehicle.OwnerID == userID);
            return View(reservations.ToList());
        }

        [Authorize(Roles = "Admin, Employee")]
        public ActionResult LocationSelect()
        {
            ViewBag.CurrentLocation = new SelectList(db.Locations, "LocationID", "LocationName");
            return View();
        }

        // GET: Reservations
        [Authorize(Roles = "Admin, Employee")]
        public ActionResult Index(int? CurrentLocation)
        {

            var reservations = db.Reservations.Where(r => r.IsComplete == false).Include(r => r.Location).Where(r => r.Location.LocationID == CurrentLocation).Include(r => r.OwnerVehicle);
            return View(reservations.ToList());
        }
        
        // GET: Reservations/Details/5
        [Authorize(Roles = "Admin, Employee")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            ViewBag.VehicleNotes = new SelectList(db.OwnerVehicles, "OwnerVehicleID", "RequestedRepairs");
            return View(reservation);
        }

        //GET: AdminCreate
        [Authorize(Roles = "Admin, Employee")]
        public ActionResult AdminCreate()
        {
            ViewBag.Owner = new SelectList(db.UserDetails, "UserID", "FullName");
            return View();
        }

        // GET: Reservations/Create
        [Authorize(Roles = "Admin, Employee, Owner")]
        public ActionResult Create(string Owner)
        {
            if (User.IsInRole("Owner"))
            {
                Owner = User.Identity.GetUserId();
                var HomeStore = db.UserDetails.Select(o => o.HomeStore).FirstOrDefault();
                ViewBag.OwnerVehicleID = new SelectList(db.OwnerVehicles.Where(o => o.OwnerID == Owner), "OwnerVehicleID", "MakeAndModel");
                ViewBag.LocationID = new SelectList(db.Locations.Where(o => o.LocationID == HomeStore && o.Reservations.Count < o.ReservationLimit), "LocationID", "LocationName");
            }

            if (User.IsInRole("Employee"))
            {
                ViewBag.LocationID = new SelectList(db.Locations.Where(o => o.Reservations.Count < o.ReservationLimit), "LocationID", "LocationName");
            }

            if (User.IsInRole("Admin"))
            {
                ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName");
            }

            if (User.IsInRole("Admin") || User.IsInRole("Employee"))
            {
                ViewBag.OwnerVehicleID = new SelectList(db.OwnerVehicles.Where(o => o.OwnerID == Owner), "OwnerVehicleID", "Make");
            }
            return View();
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Employee, Owner")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReservationID,OwnerVehicleID,LocationID,ReservationDate")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                reservation.IsComplete = false;
                db.Reservations.Add(reservation);
                db.SaveChanges();
                if (User.IsInRole("Admin") || User.IsInRole("Employee"))
                {
                    return RedirectToAction("LocationSelect");
                }
                else
                {
                    return RedirectToAction("OwnerReservation");
                }
            }

            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName", reservation.LocationID);
            ViewBag.OwnerVehicleID = new SelectList(db.OwnerVehicles, "OwnerVehicleID", "Make", reservation.OwnerVehicleID);
            return View(reservation);
        }

        // GET: Reservations/Edit/5
        [Authorize(Roles = "Admin, Employee")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName", reservation.LocationID);
            ViewBag.OwnerVehicleID = new SelectList(db.OwnerVehicles, "OwnerVehicleID", "Make", reservation.OwnerVehicleID);
            return View(reservation);
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Employee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReservationID,OwnerVehicleID,LocationID,ReservationDate")] Reservation reservation, string RequestedRepairs)
        {
            if (ModelState.IsValid)
            {
                reservation.IsComplete = false;
                db.Entry(reservation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("LocationSelect");
            }
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName", reservation.LocationID);
            ViewBag.OwnerVehicleID = new SelectList(db.OwnerVehicles, "OwnerVehicleID", "Make", reservation.OwnerVehicleID);
            return View(reservation);
        }

        // GET: Reservations/Delete/5
        [Authorize(Roles = "Admin, Employee")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [Authorize(Roles = "Admin, Employee")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reservation reservation = db.Reservations.Find(id);
            //db.Reservations.Remove(reservation);
            //db.SaveChanges();
            #region Soft Delete
            if (reservation.IsComplete.Equals(true))
            {
                reservation.IsComplete = false;
            }
            if (reservation.IsComplete.Equals(false))
            {
                reservation.IsComplete = true;
            }
            db.SaveChanges();
            #endregion
            return RedirectToAction("LocationSelect");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FSDP/Views/Reservations/AdminCreate.cshtml
@model FSDP.DATA.EF.Reservation

@{
    ViewBag.Title = "AdminCreate";
}

<h2>Select A Customer</h2>


@using (Html.BeginForm("Create", "Reservations", FormMethod.Get)) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Reservation</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.OwnerVehicle.UserDetail.FullName, "Customer", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Owner", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.OwnerVehicle.UserDetail.FullName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Next" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FSDP/Views/Reservations/Create.cshtml
@model FSDP.DATA.EF.Reservation
@{
    /**/

    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Appointment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.OwnerVehicle.OwnerID, "Vehicle", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OwnerVehicleID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OwnerVehicle.OwnerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationID, "LocationID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocationID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReservationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReservationDate, new { htmlAttributes = new { @class = "form-control datepicker", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.ReservationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@if (User.IsInRole("Admin") || User.IsInRole("Employee"))
{
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(function () {
            $(".datepicker").datepicker({
                minDate: Number(0),
                maxDate: "+1w"
            });
        });
    </script>

}

FSDP/Views/Reservations/Delete.cshtml
@model FSDP.DATA.EF.Reservation

@{
    ViewBag.Title = "Delete";
}

<h2>Complete Work Order</h2>

<h3>Is this work order complete?</h3>
<div>
    <h4>Reservation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReservationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReservationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location.LocationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.LocationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerVehicle.Make)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerVehicle.Make)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Complete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FSDP/Views/Reservations/Details.cshtml
@model FSDP.DATA.EF.Reservation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Reservation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReservationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReservationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location.LocationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.LocationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerVehicle.Make)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerVehicle.MakeAndModel)
        </dd>

        <dt>@Html.DisplayNameFor(model => model.OwnerVehicle.RequestedRepairs)</dt>
        <dd>@Html.DisplayFor(model => model.OwnerVehicle.RequestedRepairs)</dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit Repair Notes", "Edit/" + Model.OwnerVehicleID, "OwnerVehicles") |
    @Html.ActionLink("Edit", "Edit", new { id = Model.ReservationID }) |
    @Html.ActionLink("Back to List", "LocationSelect")
</p>

FSDP/Views/Reservations/Edit.cshtml
@model FSDP.DATA.EF.Reservation

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Reservation</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ReservationID)

    <div class="form-group">
        @Html.LabelFor(model => model.OwnerVehicleID, "OwnerVehicleID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("OwnerVehicleID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.OwnerVehicleID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LocationID, "LocationID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("LocationID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ReservationDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ReservationDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ReservationDate, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.OwnerVehicle.RequestedRepairs, htmlAttributes: new { @class = "control-label col-md-2" })
        @*<label>Notes</label>*@
        @*<div class="col-md-10">*@
            @*@Html.EditorFor(model => model.OwnerVehicle.RequestedRepairs, new { htmlAttributes = new { @class = "form-control" } })*@
            @*<input type="text" name="RequestedRepairs" />*@
            @*@Html.ValidationMessageFor(model => model.OwnerVehicle.RequestedRepairs, "", new { @class = "text-danger" })*@
        @*</div>
    </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "LocationSelect")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FSDP/Views/Reservations/Index.cshtml
@model IEnumerable<FSDP.DATA.EF.Reservation>

@{
    ViewBag.Title = "Index";
}

<h2>Schedule</h2>

    <p class="text-center">
        @Html.ActionLink("Create New", "AdminCreate", "Reservations", new { @id = "anchorP" })
    </p>
    <table id="data-table" class="table table-bordered">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.OwnerVehicle.CarPhoto)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ReservationDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Location.LocationName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OwnerVehicle.Make)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <img src="~/Content/Images/VehicleImages/t_@item.OwnerVehicle.CarPhoto" alt="Car Photo" title="@item.OwnerVehicle.CarPhoto" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ReservationDate.Date, "ShortDateTime")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Location.LocationName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OwnerVehicle.Make)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ReservationID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ReservationID }) |
                        @Html.ActionLink("Complete", "Delete", new { id = item.ReservationID })
                    </td>
                </tr>
            }
        </tbody>
    </table>
@section scripts{
    <script>
        $(document).ready(function () {
            $("#data-table").DataTable();
            responsive: true;
        })
    </script>
}

FSDP/Views/Reservations/LocationSelect.cshtml
@model FSDP.DATA.EF.Reservation
@{
    ViewBag.Title = "LocationSelect";
}

<h2>Select A Location/Store</h2>

@using (Html.BeginForm("Index", "Reservations", FormMethod.Get))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Reservation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Location, "Location", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CurrentLocation", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Next" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FSDP/Views/Reservations/OwnerReservation.cshtml
@model IEnumerable<FSDP.DATA.EF.Reservation>

@{
    ViewBag.Title = "Index";
}

<h2>My Appointments</h2>

<p class="text-center">
    @Html.ActionLink("Create New", "Create", "Reservations", new { @id = "anchorP" })
</p>
<table id="data-table" class="table table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ReservationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location.LocationName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OwnerVehicle.Make)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ReservationDate.Date, "ShortDateTime")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location.LocationName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OwnerVehicle.Make)
                </td>
            </tr>
        }
    </tbody>
</table>
@section scripts{
    <script>
        $(document).ready(function () {
            $("#data-table").DataTable();
            responsive: true;
        })
    </script>
}